name: Build Android APK

on:
  workflow_dispatch:    # 允许你手动点击运行

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'   # 使用稳定版即可

      - name: Build APK
        run: |
          cd simple_live_app
          flutter pub get
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: simple-live-app
          path: simple_live_app/build/app/outputs/flutter-apk/*.apk
          dependency_overrides:
  intl: 0.19.0
